spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/crypto_settlement}
spring.datasource.username=${DATABASE_USERNAME:crypto}
spring.datasource.password=${DATABASE_PASSWORD:crypto}
spring.main.banner-mode=off
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
