create table idempotency_requests (
    idempotency_key varchar(120) primary key,
    request_hash varchar(64) not null,
    settlement_id varchar(80) not null,
    status varchar(40) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table settlement_intents (
    settlement_id varchar(80) primary key,
    idempotency_key varchar(120) not null unique,
    amount numeric(19, 4) not null,
    asset varchar(20) not null,
    destination_address varchar(200) not null,
    status varchar(40) not null,
    chain_transaction_hash varchar(160),
    created_at timestamp not null,
    updated_at timestamp not null,
    version bigint not null
);

create table audit_events (
    audit_event_id bigint generated by default as identity primary key,
    event_type varchar(60) not null,
    subject_type varchar(80) not null,
    subject_id varchar(120),
    idempotency_key varchar(120),
    http_method varchar(20),
    request_path varchar(400),
    response_status integer,
    previous_status varchar(40),
    new_status varchar(40),
    message varchar(500),
    occurred_at timestamp not null
);

create index idx_audit_events_event_type on audit_events(event_type);
create index idx_audit_events_subject on audit_events(subject_type, subject_id);
create index idx_settlement_intents_idempotency_key on settlement_intents(idempotency_key);
